### ISSUE TITLE
Change the page title from "React App" to "Pokedex"

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#1]
![image](https://user-images.githubusercontent.com/81813720/194945512-6eb1c38f-0d84-4d87-9145-924905cfeab6.png)
Currently the application tab title is set to the default react title, this needs to be changed to the more appropriate "Pokedex" title instead.

**Comment by Eyesnatcher-coder** [comment]
Please assign me the issue

**Comment by XDRAGON2002** [comment]
Hi @Eyesnatcher-coder! Nice to meet you!
Actually this issue is part of a git learning session that we are holding in our institute for newcomers to opensource, so people outside the institute cannot be assigned.
Although I'm sure you'll be able to find more repos during hacktoberfest! Happy hacking!

**Comment by XDRAGON2002** [comment]
Hi @R-Yash are you a student of our institute?

**Comment by XDRAGON2002** [comment]
Sure go ahead then, you have commented on a lot other issues as well, but lets take it one at a time, let me know which issue you want to work on after you finish this issue up.

**Comment by R-Yash** [comment]
Ok I will finish this issue first
