### ISSUE TITLE
Change cursor to click

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#10]
Upon hovering over the cards the cursor should be transformed into a click icon instead.

**Comment by lil-dev16** [comment]
please @XDRAGON2002 assign this issue to me

**Comment by XDRAGON2002** [comment]
Hi @lil-dev16! Happy Hacktober!

This repository is actually being used a learning exercise for our institutes students in order to learn more about opensource projects as newcomers. So these issues are more or less supposed to be assigned to them. Although I'm sure you'll find plenty of repositories that you can contribute to here on github! Have a great day!

**Comment by lil-dev16** [comment]
oh alright thanks

**Comment by XDRAGON2002** [comment]
@lil-dev16 check the PR for review.
