### ISSUE TITLE
Round the pokemon card borders

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#11]
Rounding the edges of the cards a bit would make them look better once boxshadow and border are implemented.

**Comment by spnarkdnark** [comment]
i'll try

**Comment by XDRAGON2002** [comment]
Hi @spnarkdnark! Happy Hacktober!

This issue is actually a exercise for the students of our institute that are learning about opensource this month, I'm sure you'll find a plethora of issues to contribute to on other repositories though!

**Comment by KadhamVj23** [comment]
I Want to try it

**Comment by XDRAGON2002** [comment]
Hello @KadhamVj23! Happy Hacktoberfest!

This repo is actually being used as an exercise for the students of our institute as stated above, hence cannot be allotted to people outside the institute.

**Comment by R-Yash** [comment]
@Please assign this issue to me

**Comment by Prasun60** [comment]
@XDRAGON2002  I would like to work on this issue, can it be assigned to me.

**Comment by XDRAGON2002** [comment]
@Prasun60 a PR has been made that will close this issue once merged.
