### ISSUE TITLE
Setup React Router in the project

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#12]
Currently the project is just a single page application, in order to make it multi page, React Router needs to be set up in the project to handle routes.

**Comment by XDRAGON2002** [comment]
This feature is actually very important for future issues, and they cannot be filed before the router is setup, I'll be opening more issues once this one is completed and merged!

**Comment by XDRAGON2002** [comment]
Hi @Maryam-Momoh! Happy Hacktober!

This repository is reserved for the students of our institute to work on as an ongoing session regarding introduction to opensource, hence these issues are only to be allotted to students of the institute. I'm certain you'll be able to find other issues to work on for hacktoberfest though!

**Comment by Prasun60** [comment]
#XDRAGON2002 Please assign this issue to me.

**Comment by XDRAGON2002** [comment]
@Prasun60 Finish the other PR first and if you're interested after that then I'll assign you.

**Comment by Aaroh1** [comment]
sir wo iit roorkee jaraha h

**Comment by XDRAGON2002** [comment]
Well since most of the issues, in this repo are assigned at this point, we will have to finish up this issue ASAP, so that the new set of issues can be created.

P.S. In case this issue is not resolved in the next two days, I'll either create more issues that are independent of page routing or add support for this myself.

**Comment by sohan2410** [comment]
@XDRAGON2002 claim

**Comment by XDRAGON2002** [comment]
@sohan2410 assigned.
