### ISSUE TITLE
Change the page favicon to a more pokemon related one

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#2]
![image](https://user-images.githubusercontent.com/81813720/194945548-f419f497-ba93-47b9-871b-5bf595784c4c.png)
Currently the default react favicon is being used in the application tab next to the title, this needs to be changed to something more "pokemon-like".

**Comment by Eyesnatcher-coder** [comment]
Hey @XDRAGON2002 , please assign me the issue.

**Comment by R-Yash** [comment]
@XDRAGON2002 Please assign this issue to me

**Comment by R-Yash** [comment]
@XDRAGON2002 Can I work on this Issue?

**Comment by XDRAGON2002** [comment]
Sure, go ahead.
