### ISSUE TITLE
UI design is very simple and not very thematic with respect to pokemon.

### ISSUE THREAD

**Issue by iamhariom0228** [XDRAGON2002/POKEDEX#25]
![Screenshot (590)](https://user-images.githubusercontent.com/89256126/195503909-97d5672a-4526-423f-bc95-9aaf2b553841.png)

**Comment by iamhariom0228** [comment]
I would like to change the theme of the page i.e. background image and other changes if needed. Also the vibrant card added is not working in my laptop. @XDRAGON2002 sir, can you assign it to me?

**Comment by XDRAGON2002** [comment]
@iamhariom0228 what exactly do you want to change?

**Comment by iamhariom0228** [comment]
> @iamhariom0228 what exactly do you want to change?

The background gradient , I want to change it to the theme color related to pokemon and I  have tried it it was looking quite nice.

**Comment by iamhariom0228** [comment]
![Screenshot (594)](https://user-images.githubusercontent.com/89256126/195661861-2b0b4362-ac5d-46e8-9cb8-177498d0001c.png)
![Screenshot (595)](https://user-images.githubusercontent.com/89256126/195661919-b80dac08-ea5d-40a3-8de3-73c38baf94bc.png)

**Comment by iamhariom0228** [comment]
@XDRAGON2002  sir check it if you like or not

**Comment by XDRAGON2002** [comment]
Hm, it does look good and this also gave me an idea.

How about we implement multiple colour modes?
Like create a button similar to dark mode light mode type of button that upon click will change between the theme, the implementation is pretty much a if else statement of checking which theme should be displayed, but doing this change in React for a newcomer could be tough.

@iamhariom0228 are you up for it? If not then no problems I'll merge this one and have someone else try to implement that feature.

**Comment by iamhariom0228** [comment]
I have not learnt react yet so I can't do this for now but I will definitely try to implement it later on.

**Comment by XDRAGON2002** [comment]
Sure! Great!

**Comment by iamhariom0228** [comment]
> Sure! Great!

@XDRAGON2002 sir merge it for now if possible:)

**Comment by XDRAGON2002** [comment]
In order to merge this you will have to open a PR first. I'll merge the PR and close this issue as well.
