### ISSUE TITLE
Center the POKEDEX heading and searchbar

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#3]
![image](https://user-images.githubusercontent.com/81813720/194945658-da69866c-6484-46fc-a24c-6300d3d58b8d.png)
There is a lot of space to the left of the searchbar and heading, this needs to be resolved by centering these two items horizontally.

**Comment by Eyesnatcher-coder** [comment]
Hey @XDRAGON2002 , please assign me the issue.

**Comment by Frey0-0** [comment]
Please assign this issue to me @XDRAGON2002

**Comment by XDRAGON2002** [comment]
Hey @Eyesnatcher-coder and @Frey0-0, Happy Hacktober! 
This repo is actually participating in a month long guidance event for the students of our institute and hence is closed to people outside the institute, hence cannot be assigned to either of you.

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 I would like to resolve this issue . Can you assign this to me?

**Comment by XDRAGON2002** [comment]
Sure @ImAnshuJoshi! Go ahead!
