### ISSUE TITLE
Add border to the pokemon card blocks

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#4]
Add styling to the cards in order to have a black border around each and every pokemon div.

**Comment by Debajyoti111** [comment]
Hi @XDRAGON2002 , I am interested in working on this. Can you please assign this to me?

**Comment by XDRAGON2002** [comment]
Sure @Debajyoti111, have you gone through the README and CONTRIBUTING files to setup the project? If not go through them and feel free to ask for help here! Happy Hacking!

**Comment by XDRAGON2002** [comment]
Completed via #13
