### ISSUE TITLE
Change dull background

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#5]
The pure white background looks extremely dull, this needs to be changed, I don't have any specific design that I want to see, get creative and suggest a background that you feel will look great! Could be an image or a simple colour change may or may not be gradient based.

**Comment by epolis185** [comment]
Hi, while I am at it, might as well give this one a try as well. thank you!

**Comment by XDRAGON2002** [comment]
Hi @epolis185! Nice to meet you!

This repository is actually an exercise for the students of our institute to get familiar with git and opensource in general as they have recently started learning about it, I'm sure you'll find various other repositories that you can contribute to the month round! Cheers!

**Comment by epolis185** [comment]
Sounds good! Good luck to your students!

**Comment by R-Yash** [comment]
#XDRAGON2002  Please assign this issue to me

**Comment by Prasun60** [comment]
@XDRAGON2002 would like to work on this issue can this be assigned to me.

**Comment by XDRAGON2002** [comment]
@Prasun60 are you a student of our institute?

**Comment by XDRAGON2002** [comment]
@Prasun60 Go ahead!
