### ISSUE TITLE
Add box-shadow to the pokemon blocks

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#6]
Adding box-shadows to the cards would make them look like having depth, hence box-shadows need to be added to them.

**Comment by epolis185** [comment]
Hi, I'd like to try this one too please

**Comment by haseeb-xd** [comment]
i want to work on this

**Comment by XDRAGON2002** [comment]
Hi @haseeb-xd! #17 has just been opened which fixes this issue! Better luck next time! Happy Hacking!
