### ISSUE TITLE
Center image and title of pokemon cards

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#7]
![image](https://user-images.githubusercontent.com/81813720/194948021-ee0c2116-2a40-44e1-8295-168963f686c1.png)
Currently the title and image are not on top of one other, instead are to the left and right of each other, this needs to be fixed.

**Comment by jpacsai** [comment]
I would like to work on this, please assigne it to me

**Comment by XDRAGON2002** [comment]
Hi @jpacsai! Happy Hacktober!

This issue is actually created as an exercise for the students of our institute to work on and gain experience regarding git and opensource as they have recently started learning about opensource, though I'm sure you'll find a number of repositories that you can contribute to!

**Comment by jpacsai** [comment]
oh, sorry :D

**Comment by XDRAGON2002** [comment]
> oh, sorry :D

No need to be sorry it's okay! Have a great day! Cheers!
