### ISSUE TITLE
Stack pokemon horizontally instead of vertically

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#8]
![image](https://user-images.githubusercontent.com/81813720/194948216-5b37ec5e-17a7-4114-ae99-10e85ea8c45e.png)
Currently the pokemon cards are stacked on top of each other, it would be better if they are placed next to each other horizontally row-wise.

**Comment by epolis185** [comment]
Hi! I'd like to give this one a try

**Comment by R-Yash** [comment]
@XDRAGON2002  Please assign this issue to me
