### ISSUE TITLE
Ensure responsiveness of the page

### ISSUE THREAD

**Issue by XDRAGON2002** [XDRAGON2002/POKEDEX#9]
The page needs to be made responsive for smaller screen devices.

**Comment by XDRAGON2002** [comment]
Hi @abitsalihu! Happy Hacktoberfest!
Yes, I had a pure CSS implementation in mind for this issue (media queries).

Also actually this repository is being used as an institute session for our college students that are newcomers to opensource, so these issues are to help them gain hands on experience on projects, although I'm sure you will find various other repositories participating in hacktoberfest.

**Comment by abitsalihu** [comment]
Oh okay, hope your students have fun solving these. Good luck to them. :)

**Comment by XDRAGON2002** [comment]
Thanks! I hope so too for them haha.
Good luck to you too, great meeting you.

**Comment by abitsalihu** [comment]
Great meeting you too, have an amazing day. :)

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 i would like to work on this . Can you assign this to me?

**Comment by XDRAGON2002** [comment]
Hey @ImAnshuJoshi I'll assign you once you finish the other issue. assigned to you.

**Comment by ImAnshuJoshi** [comment]
Hey @XDRAGON2002 , i have done the PR from my side , but i guess it has also solved this issue and also centered the title and images .

**Comment by XDRAGON2002** [comment]
@ImAnshuJoshi check the PR for updates.
